In [3]:
import torch

In [4]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [5]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [7]:
a = torch.tensor([3.5])   #要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)