In [1]:
import torch

In [5]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [4]:
A * B   #两个矩阵的按元素乘法称为Hadamard积（Hadamard product），和点积的区别是不求和

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [9]:
x = torch.arange(4,dtype=torch.float32)
x , x.sum() , x.sum().item()

(tensor([0., 1., 2., 3.]), tensor(6.), 6.0)

In [11]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0 , A_sum_axis0.sum()

(tensor([40., 45., 50., 55.]), tensor(190.))

In [12]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1 , A_sum_axis1.sum()

(tensor([ 6., 22., 38., 54., 70.]), tensor(190.))

In [13]:
A.sum(axis=[0,1])

tensor(190.)

In [14]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [15]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [17]:
A.cumsum(axis=0)  #沿某个轴计算A元素的累积总和

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [18]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [19]:
torch.sum(x * y)

tensor(6.)

In [20]:
A.shape, x.shape, torch.mv(A, x)  #矩阵-向量积

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [21]:
B = torch.ones(4, 3)  #矩阵-矩阵乘法
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [23]:
u = torch.tensor([3.0, -4.0]) #L2范数
torch.norm(u)

tensor(5.)

In [24]:
torch.abs(u).sum() #L1范数（表示为向量元素的绝对值之和）

tensor(7.)